version: 1

sources:
  - name: dvd_rental
    database: dvd_rental
    schema: raw
    tables:
      - name: customer
      - name: rental
      - name: film
      - name: film_category
      - name: category
      - name: payment
      - name: inventory
      - name: country
      - name: city
      - name: address
      - name: staff
      - name: store
